### ISSUE TITLE
getChestOrientation returns incorrect results

### ISSUE THREAD

**Issue by cmburgul** [WPI-Humanoid-Robotics-Lab/tough#12]
The class function ChestControlInterface::getChestOrientation is not giving the correct tf values... There is huge offset and error is not in proportional to right values.

**Comment by ninja777** [comment]
Could not reproduce the bug.  Used the following code to test and it is returning correct values.
```
   geometry_msgs::Quaternion quat;
    chestTraj.getChestOrientation(quat);
    tf::Quaternion q;
    tf::quaternionMsgToTF(quat, q);
    double roll_c, pitch_c, yaw_c;
    tf::Matrix3x3(q).getRPY(roll_c, pitch_c, yaw_c);
```
