### ISSUE TITLE
Potential memory leaks .

### ISSUE THREAD

**Issue by AmeyaWagh** [WPI-Humanoid-Robotics-Lab/tough#26]
Objects created on heap but the memory is not freed after execution.

https://github.com/WPI-Humanoid-Robotics-Lab/tough/blob/a5b33afda4397a6ad35b027a9588e8eb94e8b04c/tough_examples/src/manipulation_examples/taskspace_planner_interactive_example.cpp#L34

```c++
while(true){..
```
can be replaced with a flag and can be set to false by user interrupt
```c++
while(RUN_STATUS){..
```

**Comment by ninja777** [comment]
@AshayAswale we can replace the condition with `ros::ok()` and outside the loop delete all the objects on heap.

**Comment by AshayAswale** [comment]
Fixed in commit https://github.com/WPI-Humanoid-Robotics-Lab/tough/commit/211bd35f3d7796dfe872d049d89471f4a5722b7f
