### ISSUE TITLE
Melodic Port

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [WPI-Humanoid-Robotics-Lab/tough#28]
Is there a plan to port this package to ROS Melodic? (The SRC 2 states using Bionic Beaver as a requirement as well).  

> 10.0 HARDWARE AND SOFTWARE SPECIFICATIONS
> Minimum System Requirements to run SRC P2 Simulation:
> ● An NVidia family GPU
> ● Intel i5 CPU or equivalent
> ● 8 GB of RAM
> ● 25GB of free disk space or more
> ● Ubuntu 18.04.2 LTS (Bionic Beaver)
> ● ROS Melodic Morenia
> ● Gazebo 9

Source:  
[Space Robotics Challenge 2 Rules](https://ninesights.ninesigma.com/apps/IMT/UploadedFiles/58/f_4b456f45f707de1b69ce4ade81ecc152/SRC_Phase_2_Official_Rules_FINAL.pdf?v=1565175894)

**Comment by ninja777** [comment]
Tough is built for humanoid robots. Parts of it can be used for perception or motion planning, but that's not what this library is designed for. 

Its usefulness for SRC2 can only be determined once the simulation software for SRC2 is released.

As for the plans to upgrade, we are  plannining to move it to ROS2 in the coming months.

**Comment by DhruvKoolRajamani** [comment]
> Tough is built for humanoid robots. Parts of it can be used for perception or motion planning, but that's not what this library is designed for.
> 
> Its usefulness for SRC2 can only be determined once the simulation software for SRC2 is released.
> 
> As for the plans to upgrade, we are plannining to move it to ROS2 in the coming months.

Unless SRC 2 changes its requirements, Tough is dependent on the humanoid_navigation package for its footstep planning as well right? A port to Dashing would require you to port this package as well (might be easier to use the ros1_bridge and simply port the nav packages to melodic.

Regardless, I'm giving it a shot and can open up a PR into a new branch (if not master) if it works successfully. I'm running Pop on Ubuntu 18 and really don't want to downgrade my OS to use this package.
