### ISSUE TITLE
Fix Nudge functionality in tough APIs

### ISSUE THREAD

**Issue by ninja777** [WPI-Humanoid-Robotics-Lab/tough#3]
In ArmControlInterface, for nudgeArmLocal and nudgeArmPelvis, the code for moving the arm is [commented](https://github.com/WPI-Humanoid-Robotics-Lab/tough/blob/019fa028b6ebf877a2ee30a20e31cc9877e2ff75/tough_control/tough_controller_interface/src/arm_control_interface.cpp#L518)

**Comment by AshayAswale** [comment]
Fixed in commit https://github.com/WPI-Humanoid-Robotics-Lab/tough/commit/e6bedbb2ca7d381c8ac45b31cb9066aef47e56e1
