### ISSUE TITLE
Tough examples need to be a different package

### ISSUE THREAD

**Issue by AmeyaWagh** [WPI-Humanoid-Robotics-Lab/tough#5]
example nodes in tough need to be a separate package

**Comment by ninja777** [comment]
navigation examples are not moved yet. Reopening the issue. 
We should also rename the files from test_xxx to xxx_example

**Comment by ninja777** [comment]
The file names are:
- [ ] test_footstep.cpp
- [ ] walk_forward.cpp
- [ ] walk_goal.cpp
- [ ] walk_rotate.cpp
- [ ] walk_steps.cpp
- [ ] walk_test.cpp
